import { WidgetDefinition, WidgetType } from '@/types/dashboard';

export const WIDGET_REGISTRY: Record<WidgetType, WidgetDefinition> = {
  'kpi-card': {
    type: 'kpi-card',
    name: 'KPI Card',
    description: 'Single metric with optional sparkline',
    icon: 'BarChart3',
    defaultSize: { w: 3, h: 2 },
    minSize: { w: 2, h: 2 },
    maxSize: { w: 4, h: 2 },
    configurable: true,
    configFields: [
      {
        key: 'metric',
        label: 'Metric',
        type: 'select',
        options: [
          { value: 'pipeline-value', label: 'Pipeline Value' },
          { value: 'avg-cap-rate', label: 'Avg Cap Rate' },
          { value: 'active-pipeline', label: 'Active Pipeline' },
          { value: 'total-deals', label: 'Total Deals' },
          { value: 'deal-velocity', label: 'Deal Velocity' },
          { value: 'saved-deals', label: 'Saved Deals' },
          { value: 'avg-cash-on-cash', label: 'Avg Cash-on-Cash' },
        ],
        default: 'pipeline-value',
      },
      { key: 'showSparkline', label: 'Show Sparkline', type: 'boolean', default: true },
      { key: 'showChange', label: 'Show Change', type: 'boolean', default: true },
    ],
  },
  'deals-status-chart': {
    type: 'deals-status-chart',
    name: 'Deals by Status',
    description: 'Donut chart of pipeline status',
    icon: 'PieChart',
    defaultSize: { w: 5, h: 4 },
    minSize: { w: 4, h: 3 },
    maxSize: { w: 8, h: 5 },
    configurable: false,
  },
  'recent-deals': {
    type: 'recent-deals',
    name: 'Recent Deals',
    description: 'List of recent deals',
    icon: 'List',
    defaultSize: { w: 7, h: 4 },
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 6 },
    configurable: true,
    configFields: [
      {
        key: 'limit',
        label: 'Number of deals',
        type: 'select',
        options: [
          { value: '5', label: '5 deals' },
          { value: '10', label: '10 deals' },
        ],
        default: '5',
      },
    ],
  },
  'ai-insights': {
    type: 'ai-insights',
    name: 'AI Insights',
    description: 'AI-powered recommendations',
    icon: 'Sparkles',
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 5, h: 6 },
    configurable: false,
  },
  'quick-actions': {
    type: 'quick-actions',
    name: 'Quick Actions',
    description: 'Shortcut buttons',
    icon: 'Zap',
    defaultSize: { w: 3, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 4, h: 4 },
    configurable: false,
  },
  'pipeline-funnel': {
    type: 'pipeline-funnel',
    name: 'Pipeline Funnel',
    description: 'Deal stage funnel',
    icon: 'Filter',
    defaultSize: { w: 4, h: 4 },
    minSize: { w: 3, h: 3 },
    maxSize: { w: 6, h: 5 },
    configurable: false,
  },
  'portfolio-map': {
    type: 'portfolio-map',
    name: 'Portfolio Map',
    description: 'Property locations map',
    icon: 'Map',
    defaultSize: { w: 6, h: 4 },
    minSize: { w: 4, h: 3 },
    maxSize: { w: 12, h: 6 },
    configurable: false,
  },
  'cash-flow-summary': {
    type: 'cash-flow-summary',
    name: 'Cash Flow',
    description: 'Income vs expenses',
    icon: 'DollarSign',
    defaultSize: { w: 4, h: 3 },
    minSize: { w: 3, h: 2 },
    maxSize: { w: 6, h: 4 },
    configurable: false,
  },
};

export const getWidgetDefinition = (type: WidgetType) => WIDGET_REGISTRY[type];
export const getAllWidgets = () => Object.values(WIDGET_REGISTRY);
