import { NextRequest, NextResponse } from 'next/server';
import { supabaseAdmin } from '@/lib/supabase/admin';

export async function GET(
    request: NextRequest,
    { params }: { params: Promise<{ id: string }> }
) {
    try {
        const { id: dealId } = await params;

        // Fetch deal with metrics
        const { data: deal, error: dealError } = await supabaseAdmin
            .from('deals')
            .select('*')
            .eq('id', dealId)
            .single();

        if (dealError || !deal) {
            return NextResponse.json({ error: 'Deal not found' }, { status: 404 });
        }

        const { data: metrics } = await supabaseAdmin
            .from('deal_metrics')
            .select('*')
            .eq('deal_id', dealId)
            .single();

        // Generate a simple text-based "PDF" for now
        // In production, you'd use a library like pdf-lib or puppeteer
        const content = `
DEAL ANALYSIS REPORT
====================

Property: ${deal.address_line1}
         ${deal.city}, ${deal.state} ${deal.zip}

PROPERTY DETAILS
----------------
List Price:    $${deal.list_price?.toLocaleString() || 'N/A'}
Beds/Baths:    ${deal.beds || '-'} / ${deal.baths || '-'}
Square Feet:   ${deal.sqft?.toLocaleString() || 'N/A'}
Year Built:    ${deal.year_built || 'N/A'}
Property Type: ${deal.property_type || 'N/A'}

FINANCIAL METRICS
-----------------
Est. Rent:       $${deal.estimated_rent?.toLocaleString() || 'N/A'}/month
Cap Rate:        ${metrics?.cap_rate?.toFixed(2) || 'N/A'}%
Cash-on-Cash:    ${metrics?.cash_on_cash?.toFixed(2) || 'N/A'}%
Monthly CF:      $${metrics?.monthly_cash_flow?.toLocaleString() || 'N/A'}
DSCR:            ${metrics?.dscr?.toFixed(2) || 'N/A'}
NOI:             $${metrics?.noi?.toLocaleString() || 'N/A'}

LOAN DETAILS
------------
Down Payment:    $${metrics?.down_payment?.toLocaleString() || 'N/A'}
Loan Amount:     $${metrics?.loan_amount?.toLocaleString() || 'N/A'}
Monthly P&I:     $${metrics?.monthly_mortgage?.toLocaleString() || 'N/A'}

STATUS
------
Current Status: ${deal.status?.toUpperCase() || 'NEW'}
Days on Market: ${deal.days_on_market || 'N/A'}

Generated by ScoutzOS on ${new Date().toLocaleDateString()}
        `.trim();

        // Return as plain text file (would be PDF in production)
        return new NextResponse(content, {
            headers: {
                'Content-Type': 'text/plain',
                'Content-Disposition': `attachment; filename="deal-${deal.address_line1.replace(/[^a-zA-Z0-9]/g, '-')}.txt"`,
            },
        });
    } catch (error: unknown) {
        console.error('Export PDF error:', error);
        return NextResponse.json({ error: 'Failed to export' }, { status: 500 });
    }
}
